name: Mise à jour quotidienne des articles géopolitiques

# Le workflow s'exécute tous les jours à 03h00 UTC et peut aussi être déclenché
# manuellement via l'interface GitHub.  Il utilise un script Python pour
# récupérer un nouvel article depuis un flux RSS, créer une page HTML et
# mettre à jour la page d'index.  Les modifications sont ensuite
# automatiquement commit et poussées sur le dépôt.

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install feedparser
      - name: Run update script
        run: python update_articles.py
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # Le commit échouera s'il n'y a pas de modifications. On ignore l'erreur.
          git commit -m "Mise à jour automatique des articles géopolitiques" || echo "Pas de changements à commettre"
          git push